Arkavo/Arkavo/Arkavo.xcdatamodeld/Arkavo.xcdatamodel/contents
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/Services/OpenTDFWrapper.h
Arkavo/Arkavo/Services/OpenTDFWrapper.mm
Arkavo/ci_scripts/ci_pre_xcodebuild.sh

- Decrypts the item.  The item content is a random string
- CI: remove unused headers

TDF decrypt

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/ci_scripts/ci_pre_xcodebuild.sh
README.md

- only arm64
- separate ios and macos build folders

Release build fixes

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/City.swift
Arkavo/Arkavo/CityLabel.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/WebSocketManager.swift
Arkavo/ArkavoTests/CityTests.swift

Added demo code showing geo points.  Primary focus is to show the performance of the Swift OpenTDFKit and the RustKAS.
The demo steps:
1. create geo points
2. nano encrypt geo points
3. nano decrypt geo points
4. display geo points

MapKit Demo

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

https://github.com/arkavo-org/OpenTDFKit/releases/tag/1.0.0

OpenTDFKit 1.0.0

---

Arkavo/Arkavo/ContentView.swift

Refactor account selection and clean up UI components
Updated account selection handling to use a segmented picker in the iOS layout. Reorganized the demo and authentication buttons into a more accessible gear menu, and added a state variable to toggle the city info overlay.
Fixed iOS layout and account buttons

UI demo section

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/Thought.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Arkavo/WordCloudView.swift

Added WordCloudView.swift including its implementation and necessary dependencies. Updated the project file to include the new WordCloudView.swift.
Introduced `sender` property in `Thought` struct with related initializations and helper methods. Refactored `ThoughtStreamView` to display sender information and simplified UI logic by consolidating thoughts and adjusting message layout accordingly.

WordCloudView

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/Account.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/Content.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/Profile.swift
Arkavo/Arkavo/SecureStream.swift
README.md

Added:
- Entity diagram
- SwiftData Models:
- Account
- Profile
- Content
- SecureStream

Account, Profile, Content

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/Account.swift
Arkavo/Arkavo/AccountProfileView.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/Profile.swift
Arkavo/Arkavo/Stream.swift
Arkavo/Arkavo/StreamProfileView.swift
Arkavo/Arkavo/Thought.swift
Arkavo/Arkavo/ThoughtStreamView.swift

Introduced views for Compact, Detailed, and Creation profiles for both Stream and Account, encapsulating profile information, validation, and stream participant handling. Updated project references and corrected data model definitions and imports for streamlined profile management.
Profile name shows in ThoughtStream

Stream Profile, Account Profile views

---

Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/WordCloudView.swift
README.md

Updated the `ArkavoView` to simplify the user interface by restructuring the view layout using `GeometryReader` and removing the redundant `showMap` state. Improved overall readability and maintainability of the code by consolidating UI elements and reducing unnecessary nesting.

Fix Navigation menu

---

Arkavo/Arkavo/ArkavoView.swift

Refactor camera position handling and include locale-based centering on the user's country. Improve animation fluidity and ensure async actions are handled correctly within Task blocks for better responsiveness.
Locale can also be used to identify which country's KAS (keys hosted in the country)

Update map behavior and add locale-based centering

---

Arkavo/Arkavo/AccountProfileView.swift

Bug # 25 Added a "X" to Create Profile and View Profile sheets to make it obvious how to quit in both iOS and MacOS

Add "X" to Create/View Profile sheet (Bug # 25) Pull Request

---

.gitignore
Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/Account.swift
Arkavo/Arkavo/Arkavo.entitlements
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/AuthenticationManager.swift
Arkavo/Arkavo/Info.plist
Arkavo/Arkavo/PersistenceController.swift
Arkavo/Arkavo/Stream.swift
Arkavo/Arkavo/StreamManagementView.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Arkavo/WebSocketManager.swift

This pull request implements account persistence and improves authentication management across the app. Key changes include:
- Refactored authentication management to consolidate account handling within `AuthenticationViewModel`
- Introduced `AttestationEnvelope` and `AttestationEntity` models for improved data structure
- Replaced `AccountManager` with `AccountViewModel`
- Streamlined initialization and usage in app views
- Implemented keychain integration for EC signing key and user accounts
- Added `PersistenceController` for better structured data management
- Updated `signIn` method to be async and handle attestation
- Refactored authentication to use tokens instead of envelopes
- Improved authentication response handling
- Added `X-Auth-Token` header for HTTP requests
- Refactored …

Account Persistence - Authentication Token

---

Arkavo/Arkavo/WebSocketManager.swift

Implemented a reconnect mechanism with a maximum of 5 attempts when the WebSocket disconnects. Added methods to start and stop a timer that handles reconnection logic. Enhanced WebSocket connection management to reset reconnection attempts on successful connection.

WebSocket reconnection

---

Arkavo/Arkavo/AccountProfileView.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/WebSocketManager.swift

Introduced an initial view for user onboarding and enhanced the profile creation process with async task handling. Simplified async functions and task handling to ensure smoother transitions and more reliable data management. 
Refactored the UI to improve clarity and corrected spacing inconsistencies.

Register flow

---

Arkavo/Arkavo/AccountProfileView.swift
Arkavo/Arkavo/PersistenceController.swift
Arkavo/Arkavo/Profile.swift

Added "radio" buttons for Interests. updated database

Updated Create Profile

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/Arkavo.entitlements
Arkavo/Arkavo/AuthenticationManager.swift

Replaced old bundle identifiers with new ones using "com.arkavo" prefix. Changed code signing style from Automatic to Manual and cleared the development team field in project settings.

Bundle identifier

---

Arkavo/Arkavo/AccountProfileView.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/AuthenticationManager.swift
Arkavo/Arkavo/PersistenceController.swift
Arkavo/Arkavo/StreamManagementView.swift

Removed redundant `@Environment(\.modelContext)` and replaced async persistence methods with synchronous equivalents. Streamlined profile save logic and improved initialization of view models within the app.

Simplify profile creation and persistence handling

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/StreamCloudView.swift
Arkavo/Arkavo/StreamMapView.swift
Arkavo/Arkavo/StreamView.swift
Arkavo/Arkavo/ThoughtView.swift
Arkavo/Arkavo/WelcomeView.swift

Renamed `WordCloudView` to `StreamCloudView` and `ThoughtStreamView` to `ThoughtView`. Introduced `WelcomeView` for onboarding and `StreamMapView` for map-based visualizations. Updated project file references accordingly.

Refactor Stream

---

Arkavo/Arkavo/VideoCaptureManager.swift
Arkavo/Arkavo/VideoStreamView.swift

Description:
This PR introduces a series of refactors and new functionalities aimed at improving the video capture experience within the app. Key changes include:
Major Changes:
1.	Orientation Handling Improvements:
•	Refactor orientation handling by switching from UIDeviceOrientation to UIInterfaceOrientation for more accurate management of device orientation changes.
•	Enhanced pixel buffer creation with proper attributes.
•	Added thread safety to kasPublicKey updates.
•	Removed deprecated and unnecessary color correction functionality.
2.	Refactor VideoCaptureManager to VideoCaptureViewController:
•	Moved VideoCaptureManager logic into a new UIViewController subclass (VideoCaptureViewController) for better integration with UIKit.
•	Reorganized camera permissions, session setup, and …

Video API fix

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/WelcomeView.swift
Arkavo/Localizable.xcstrings

Added localizable.xcstrings file and localized the WelcomeView.swift file. Added translations in Spanish for all strings (except "blurb").

Added Spanish Localization to WelcomeView

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/Arkavo.entitlements
Arkavo/Arkavo/Info.plist
Arkavo/Arkavo/StreamProfileView.swift
Arkavo/Arkavo/ThoughtStreamView.swift

Integrated share button for iOS and macOS platforms. Updated URL links for app entitlements and sharing features. Also included mock data for previews and adjusted the marketing version number in the project settings.
```
https://app.arkavo.com/stream/7fd7a172424d6ff8aae1b949dba9c5b911df0a7fbe84836315273516d1486aa1
```
TODO handler for opening the Stream link in app

Share Stream

---

Arkavo/Arkavo/ArkavoService.swift

Refactor asynchronous tasks to use Swift concurrency
Replaced dispatch queues with Swift concurrency features by implementing asynchronous handling within `Task`. Separated responsibilities into specific functions for handling different payload types, improving code readability and maintainability.

Fix for video concurrently-executing code

---

Arkavo/Arkavo/WelcomeView.swift
Arkavo/Localizable.xcstrings

Revised text strings in WelcomeView for clarity and conciseness. Updated BulletPoint structure to emphasize key terms and ensure proper text styling. Adjusted relevant localization keys to keep the translations up-to-date.

WelcomeView rev

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/AccountProfileBadge.swift
Arkavo/Arkavo/AccountProfileView.swift
Arkavo/Arkavo/ActivityService.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/Profile.swift
Arkavo/Arkavo/StreamProfileBadge.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Localizable.xcstrings

- StreamProfileBadge Component: Adds a new SwiftUI view for displaying stream profiles with detailed information such as name, image, description, tags, members, and activity level.
- AccountProfileBadge and ActivityService: Adds components to display detailed user profiles, pulling dynamic data from ActivityServiceModel. The Profile model now includes location and security attributes.
- ThoughtStreamView Layout Enhancements: Refactors ThoughtStreamView to use GeometryReader for improved layout flexibility. Streamlines the message input area and reduces redundant code.

Profile Badges

---

Arkavo/Arkavo/StreamLoadingView.swift
Arkavo/Arkavo/ThoughtStreamView.swift

Modify StreamLoadingView and ThoughtStreamView for cross-platform compatibility.
Refactored StreamLoadingView to conditionally use fullScreenCover for iOS and sheet for other platforms. Updated ThoughtStreamView to conditionally enable back buttons, image picker, and camera picker based on the platform. Made minor adjustments to background colors for improved UI consistency.

fix Mac build

---

Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/StreamProfileView.swift
Arkavo/Arkavo/StreamView.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Localizable.xcstrings

Make lines blue. Changed "MINE" to "My Streams". Changed "Empty" to "No Active Streams". Added text to + icon "Create New Stream".
Create Stream View: Changed "Name" to "What are we discussing". Changed "Description" to "Topic of Interest". Inserted text box explaining what Stream Is. What it does.
Hamburger Menu View: Change List to Streams
Stream View: Add "X" to close. Add text "Invite Friends" to share icon

Stream List View: Removed Gray circle background of Hamburger Menu

---

Arkavo/Arkavo/AccountView.swift
Arkavo/Arkavo/ArkavoService.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/IDCardScannerViewController.swift
Arkavo/Arkavo/StreamMapView.swift
Arkavo/Arkavo/StreamProfileView.swift
Arkavo/Arkavo/StreamView.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Arkavo/VideoCaptureManager.swift
Arkavo/Arkavo/VideoStreamView.swift

A comprehensive update focusing on video streaming improvements, platform compatibility, and code optimization.
Key Changes:
- Added visionOS platform support with conditional feature flags
- Enhanced video capture functionality with orientation handling and async processing
- Optimized image processing pipeline with simplified JPEG compression
- Improved code quality through refactoring and dependency reduction
Technical Details:
- Implemented device orientation handling for video capture
- Reworked NanoTDF processing with CheckedContinuation
- Synchronized camera access updates with main thread
- Fixed indentation in multiple Swift files
- Streamlined StreamMapView by removing unnecessary dependencies

Video Stream

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo.xcodeproj/xcshareddata/xcschemes/Arkavo.xcscheme
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/ProtectorView.swift
Arkavo/Arkavo/VideoStreamView.swift
Arkavo/Localizable.xcstrings

Included the new `ProtectorView` SwiftUI view, which allows users to navigate through screens for content protection, including introduction, information, settings, privacy, scanning, impact, and dashboard views. This view aims to help users protect content creators' work across social networks by enabling scanning and tracking unauthorized uses.
UI is for demo purposes only

Content Protector

---

Arkavo/Arkavo/ProtectorProcessor.swift

Key Changes:
- Replaced Float16 with Float: Since Float16 is not available in macOS, I replaced all instances of Float16 with Float.

macOS float fix

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Arkavo/Arkavo/ArkavoService.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/ArkavoWebSocket.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/ProtectorService.swift
Arkavo/Arkavo/StreamService.swift
Arkavo/Arkavo/ThoughtService.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Arkavo/VideoCaptureManager.swift

---
**Description:**
- Refactored various functions to be asynchronous using `await` for remote calls.
- Introduced a new `ArkavoWebSocket` class to handle WebSocket connections for real-time interactions.
- Updated the OpenTDFKit package to version 3.0.0.

OpenTDFKit 3

---

.gitignore
Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo.xcodeproj/xcuserdata/paul.xcuserdatad/xcschemes/xcschememanagement.plist
Arkavo/Arkavo/PatreonService.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/ArkavoCreator/ArkavoCreator.entitlements
Arkavo/ArkavoCreator/ArkavoCreatorApp.swift
Arkavo/ArkavoCreator/Assets.xcassets/AccentColor.colorset/Contents.json
Arkavo/ArkavoCreator/Assets.xcassets/AppIcon.appiconset/Contents.json
Arkavo/ArkavoCreator/Assets.xcassets/Contents.json
Arkavo/ArkavoCreator/ContentManagerView.swift
Arkavo/ArkavoCreator/ContentView.swift
Arkavo/ArkavoCreator/PatronManagementView.swift
Arkavo/ArkavoCreator/Preview Content/Preview Assets.xcassets/Contents.json
Arkavo/ArkavoCreatorTests/ArkavoCreatorTests.swift
Arkavo/ArkavoCreatorUITests/ArkavoCreatorUITests.swift
Arkavo/ArkavoCreatorUITests/ArkavoCreatorUITestsLaunchTests.swift
Arkavo/ArkavoSocial/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Arkavo/ArkavoSocial/Package.swift
Arkavo/ArkavoSocial/Sources/ArkavoSocial/ArkavoSocial.swift
Arkavo/ArkavoSocial/Sources/ArkavoSocial/KeychainManager.swift
Arkavo/ArkavoSocial/Sources/ArkavoSocial/PatreonAuthenticationManager.swift
Arkavo/ArkavoSocial/Sources/ArkavoSocial/PatreonClient.swift
Arkavo/ArkavoSocial/Tests/ArkavoSocialTests/ArkavoSocialTests.swift
Arkavo/Localizable.xcstrings

This pull request refactors the Patreon authentication into its own module for better organization. It also adds new UI tests and content management views, enhancing functionality and test coverage within the app.

ArkavoCreator macOS, ArkavoSocial package

---

ArkavoCreator/ArkavoCreator/ArkavoCreatorApp.swift
ArkavoCreator/ArkavoCreator/PatreonView.swift
ArkavoCreator/ArkavoCreator/WebView.swift
ArkavoSocial/Sources/ArkavoSocial/PatreonClient.swift

Refactored OAuth handling and enhanced WebView navigation. Cleaned up code by removing print statements and unused token handling. Made improvements to `PatreonClient.swift` and `PatreonView.swift`.

Fix Patreon login

---

ArkavoCreator/ArkavoCreator/ArkavoCreatorApp.swift
ArkavoCreator/ArkavoCreator/ContentView.swift
ArkavoCreator/ArkavoCreator/PatreonView.swift
ArkavoCreator/ArkavoCreator/RedditView.swift
ArkavoCreator/ArkavoCreator/WebView.swift
ArkavoSocial/Sources/ArkavoSocial/PatreonClient.swift
ArkavoSocial/Sources/ArkavoSocial/RedditClient.swift

- Add Reddit client integration with token management via keychain.
- Patreon isCreator check
- Implement stored token loading and saving mechanisms for authentication state.
- Manage token refresh and logout processes for secure session management.

Patreon Reddit Dashboard

---

ArkavoCreator/ArkavoCreator/ArkavoCreatorApp.swift
ArkavoCreator/ArkavoCreator/ContentView.swift
ArkavoCreator/ArkavoCreator/MicroblogView .swift
ArkavoCreator/ArkavoCreator/PatreonView.swift
ArkavoSocial/Sources/ArkavoSocial/MicropubClient.swift

- Micropub client
- OAuth login
- Dashboard widget

Micro.blog client

---

.gitignore
ArkavoCreator/ArkavoCreator/ArkavoCreatorApp.swift
ArkavoCreator/ArkavoCreator/ContentManagerView.swift
ArkavoCreator/ArkavoCreator/ContentView.swift
ArkavoCreator/ArkavoCreator/PatreonView.swift

- Renamed navigation titles and enum case names from **"Content Manager"** to **"Workflow"** for better clarity and alignment.
- Enhanced navigation logic to integrate the new settings interface and support client authentication handling within toolbars.
- Added advanced options and restructured templates for better usability.
- Improved message preview functionality, enhancing the messaging experience.
- Introduced an `AppState` class to manage user feedback settings using `UserDefaults`.
- Added a settings option to enable or disable the feedback button, providing more control to users.
- Modernized layout using a grid system to better organize feature cards.
- Introduced new components: **FeatureCard** and **PreviewAlert** for improved user interaction.
- Updated text styling for …

Feature preview

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ChatView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/DiscordView.swift
Arkavo/Arkavo/PatreonView.swift
ArkavoCreator/ArkavoCreator.xcodeproj/project.pbxproj
ArkavoCreator/ArkavoCreator/ArkavoCreator.entitlements
ArkavoCreator/ArkavoCreator/ArkavoCreatorApp.swift

- Removed unnecessary entitlements related to network and downloads to enhance security.
- Added new `DiscordView` and `ChatView` for improved messaging and server functionalities.
- Implemented a `ContentView` with tabbed navigation.
- Updated project files for integration and versioning to 2.0.

Arkavo v2 UI

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/BlueskyView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/DiscordView.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/TikTokView.swift
Arkavo/Arkavo/VideoCaptureManager.swift
Arkavo/Localizable.xcstrings

- Simplified tab navigation
- Added collapsible menu with auto-collapse feature
- Improved user interaction and overall UI/UX
- BlueskyView and ProfileView Enhancements
- Added BlueskyView.
- Refactored ProfileView structure.
- General Refactoring and New Views
- Improved code maintainability.
- Added new views for extended functionality.
- DiscordView Updates
- Refactored for UI consistency.
- Added chat sheet for selected channels.
- TikTok Feed Improvements
- Optimized feed performance.
- Added advanced interactions.
- Tab Navigation Enhancements
- Added collapsible menu support.
- Simplified CreatorListView.

Refactor tab navigation and enhance UX.

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/BlueskyView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/DiscordCreateView.swift
Arkavo/Arkavo/DiscordView.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/TikTokView.swift
Arkavo/Localizable.xcstrings

- Integrated `showCreateView` binding for improved state management
- Removed outdated Settings section from ProfileView
- Enhanced `PatreonView` for dynamic updates using `showCreateView`.
- Refactor DiscordView and implement server creation flow

Universal Create Button 

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ChatView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/DiscordCreateView.swift
Arkavo/Arkavo/DiscordView.swift
Arkavo/Arkavo/PatreonSupportView.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/Thought.swift
Arkavo/Arkavo/TikTokView.swift
Arkavo/Arkavo/VideoManager.swift
Arkavo/Localizable.xcstrings

- Group creation
- Group share button on Feed view
- Share button takes to Group chat
https://www.youtube.com/shorts/n6dvWPML_uw

Video sharing to Group

---

Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoService.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/BlueskyView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/DiscordCreateView.swift
Arkavo/Arkavo/DiscordView.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/ProtectorService.swift
Arkavo/Arkavo/ProtectorView.swift
Arkavo/Localizable.xcstrings
ArkavoSocial/Sources/ArkavoSocial/ArkavoClient.swift

- Decoupled `ProtectorService` from `ArkavoService`.
- Implemented `ObservableObject` for state management.
- Updated views and navigation for better modularity and maintainability.
- Replaced `ArkavoService` with `ArkavoClient` to support WebAuthn authentication.
- Enhanced security with WebSocket communication and token handling.
- Introduced immersive TikTok-style feed layout.
- Added swipe navigation and `BlueskyFeedViewModel` for post management.
- Improved UI rendering and removed unused localization strings.
- Removed debug print statements for a cleaner codebase.
- Streamlined UI logic by removing unused frame calls and enhancing layout consistency.

Protector Service and  Arkavo Client

---

Arkavo/Arkavo/Account.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoView.swift
Arkavo/Arkavo/AuthenticationManager.swift
Arkavo/Arkavo/ProtectorProcessor.swift
Arkavo/Arkavo/ProtectorRedditScanner.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Localizable.xcstrings
ArkavoCreator/ArkavoCreator.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
ArkavoSocial/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
ArkavoSocial/Package.resolved
ArkavoSocial/Package.swift
ArkavoSocial/Sources/ArkavoSocial/ArkavoClient.swift
ArkavoSocial/Sources/ArkavoSocial/KeychainManager.swift

- Refactor authentication and error handling architecture 
- Updated compactMap usage and integrated OpenTDFKit dependency
- Enhanced connection handling with detailed logging
- Added support for elliptic-curve key exchange
- Streamlined authentication and error handling architecture

ArkavoService

---

Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ChatView.swift
Arkavo/Arkavo/GroupChatView.swift
Arkavo/Arkavo/GroupCreateView.swift
Arkavo/Arkavo/Stream.swift
Arkavo/Arkavo/StreamLoadingView.swift
Arkavo/Localizable.xcstrings
ArkavoSocial/Sources/ArkavoSocial/ArkavoClient.swift

- **Stream Sharing & Deep Linking**: Added sharing for streams and enhanced deep linking with better URL handling, navigation updates, and refined loading views with retry and error states.
- **Stream Caching with Policy Encryption**: Implemented `sendStreamCacheEvent` for caching streams with remote policy encryption via FlatBuffers. Updated sharing flow with caching logic and integrated `encryptRemotePolicy` in `ArkavoClient`.
- **Group & Chat View Refactor**: Improved `ArkavoClient` integration with `Delegate` compliance for encrypted streams, rewrapped keys, and data decryption. Enhanced error handling.
- **Stream Code Cleanup**: Refactored stream logic for clarity and reusability, added deduplication checks, database validations, and removed unused features like `onShare` callbacks. …

Invite to Group Chat

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ChatView.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/CreatorSupportView.swift
Arkavo/Arkavo/CreatorView.swift
Arkavo/Arkavo/PatreonView.swift
Arkavo/Arkavo/PostFeedView.swift
Arkavo/Arkavo/StreamProfileView.swift
Arkavo/Arkavo/Thought.swift
Arkavo/Arkavo/ThoughtStreamView.swift
Arkavo/Arkavo/VideoCreateView.swift
Arkavo/Arkavo/VideoFeedView.swift
Arkavo/Arkavo/VideoManager.swift
Arkavo/Localizable.xcstrings

- Incorporated structured metadata (ratings, purposes, and content formats) into video creation workflow.
- Updated stream creation policies and linked metadata effectively.
- Improved debugging outputs and removed deprecated/redundant code.
- Refactored video orientation handling with updated APIs and frame adjustments for rotation and aspect ratio.
- Added video analysis and compression improvements.
- Removed unused intermediate HLS segment creation and redundant export methods.
- Optimized video compression logic using AVAssetExportSession presets for efficient processing.
- Replaced `CompleteButton` with `SendButton` featuring enhanced feedback and localization support.
- Integrated collapsible action buttons with smooth animations for improved interaction flow.
- Introduced …

Video orientation fix, Profile fix

---

Arkavo/Arkavo/GroupChatView.swift
Arkavo/Arkavo/GroupCreateView.swift
Arkavo/Localizable.xcstrings

- Updated variable names, UI text, and views for clarity
- Adjusted TTL for group messages
- Added sharing feature for group cards

Fix group share

---

Arkavo/Arkavo/AccountProfileBadge.swift
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ArkavoPolicy.swift
Arkavo/Arkavo/ChatViewModel.swift
Arkavo/Arkavo/CreatorView.swift
Arkavo/Arkavo/GroupChatView.swift
Arkavo/Arkavo/MetadataServiceModel.swift
Arkavo/Arkavo/PersistenceController.swift
Arkavo/Arkavo/PostFeedView.swift
Arkavo/Arkavo/Profile.swift
Arkavo/Arkavo/Thought.swift
Arkavo/Arkavo/ThoughtView.swift
Arkavo/Arkavo/VideoCreateView.swift
Arkavo/Arkavo/VideoFeedView.swift
Arkavo/Arkavo/VideoFeedViewModel.swift
Arkavo/Localizable.xcstrings
ArkavoSocial/Sources/ArkavoSocial/ArkavoClient.swift
idl/metadata.fbs

- Added methods to fetch user profiles by handle or public ID:
- Handles errors for invalid URLs, 404 responses, and other invalid responses.
- Introduced `ArkavoProfile` struct to represent profile data.
- Implemented `validateStreams` function to ensure required streams (e.g., video or post) exist:
- Refactored repeated validation code in `saveChanges` for better maintainability.
- Added error handling and streamlined post-validation saving processes.
- Added contributor creation logic in `VideoFeedViewModel`:
- Extracts metadata from the policy body to initialize a contributor.
- Defaults to a generic contributor if metadata is unavailable.
- Introduced the "creator" field in metadata for enhanced tracking:
- Added parsing, validation, and FlatBuffer updates.
- Updated views and models …

Fetch Profile

---

Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/ChatView.swift
Arkavo/Arkavo/ChatViewModel.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/CreatorView.swift
Arkavo/Arkavo/GroupChatView.swift
Arkavo/Arkavo/GroupCreateView.swift
Arkavo/Arkavo/PersistenceController.swift
Arkavo/Arkavo/PostFeedView.swift
Arkavo/Arkavo/VideoCreateView.swift
Arkavo/Arkavo/VideoFeedView.swift
Arkavo/Arkavo/VideoFeedViewModel.swift
Arkavo/Localizable.xcstrings

- Replaced direct `Stream` object references with a `streamPublicID` to improve abstraction and optimize memory usage.
- Updated models, views, and persistence logic to align with the new approach, ensuring data consistency and easier maintainability.
- Introduced the ability for users to add a description to videos during recording.
- Embedded these descriptions as custom metadata within the video file.
- Adjusted compression and export processes to seamlessly incorporate the new description metadata.
- Enhanced the UI to display video descriptions, improving user experience and content clarity.

Fix Video chat and description

---

Arkavo/Arkavo/ArkavoMessageRouter.swift
Arkavo/Arkavo/ArkavoPolicy.swift
Arkavo/Arkavo/GroupChatView.swift
Arkavo/Arkavo/Profile.swift
Arkavo/Arkavo/VideoCreateView.swift
Arkavo/Arkavo/VideoFeedView.swift
Arkavo/Arkavo/VideoFeedViewModel.swift
ArkavoSocial/Sources/ArkavoSocial/ArkavoClient.swift

- Updated data conversion logic in `VideoFeedViewModel` to ensure correct metadata usage.
- Applied UTF-8 encoding in `Profile` to prevent fatal errors caused by improper character handling.
- Removed the unused `getProfile` method from `ArkavoMessageRouter` for improved code cleanliness.
- Added safeguards to prevent duplicate message processing.
- Implemented graceful error handling to ensure stability during edge cases.
- Introduced debouncing mechanisms to handle rapid user interactions effectively.
- Commented out redundant debug print statements across multiple files to clean up logs and enhance performance.

Fix Video queue

---

Arkavo/Arkavo/CreatorView.swift
Arkavo/Arkavo/PostFeedView.swift
Arkavo/Localizable.xcstrings

- Replaced `Thought` with a new `Post` model
- Updated views, view models, and actions
- Enhanced CreatorView with modularization
- Adjusted feed rendering using grid layouts

Fix Post feed

---

Arkavo/Arkavo/ArkavoApp.swift

Add return value for successful login flow
In this pull request, a return value is added to indicate a successful login flow. The function now returns `true` when token saving and data persistence are successful, allowing better flow control for the caller to handle the success state explicitly.
Closes #111

Fix Registration error

---

Arkavo/Arkavo.xcodeproj/project.pbxproj
Arkavo/Arkavo/ArkavoApp.swift
Arkavo/Arkavo/BlockedProfile.swift
Arkavo/Arkavo/ContentView.swift
Arkavo/Arkavo/CreatorView.swift
Arkavo/Arkavo/GroupView.swift
Arkavo/Arkavo/PostFeedView.swift
Arkavo/Arkavo/ReportView.swift
Arkavo/Arkavo/VideoCreateView.swift
Arkavo/Arkavo/VideoFeedView.swift
Arkavo/Arkavo/VideoFeedViewModel.swift
Arkavo/Arkavo/VideoManager.swift
Arkavo/Localizable.xcstrings

- Introduced a unified `ViewModel` protocol to standardize ViewModel implementations across the app.
- Refactored existing ViewModels to conform to the new protocol.
- Implemented a generic factory method for streamlined ViewModel creation.
- Improved tooltip interactions and added contextual empty-state messages for better UX.
- Simplified tooltip timing and activation logic by adjusting inactivity durations.
- Repurposed the `isAwaiting` state for empty content checks.
- Improved `CreatorView` UI by fully expanding the bio text frame for better readability.
- Added a check to prevent saving the bio if no changes were made.
- Updated shared state to handle empty bio cases, ensuring proper UI behavior.
- Made the `videos` property `private(set)` to prevent unintended modifications.
- …

Report send
